### PR TITLE
Allow user to set icon size in settings

### PR DESCRIPTION
**Pull request by mswiszcz**
This PR allows user to set icon size in settings, making it easier to move from this:

before

to this:
after

Here's the new option:

newoption

May need some tweaking as I see the icon is not properly centered, not sure though if it's a problem with this or not related.

One commit is optional as Atom automatically removed unused whitespace for me.

Hope you like it :smile:

### CODE REVIEW

**Comment by dscso** [comment]
Please add this feature... I have a High DPI screen, and the icons are looking horrible... this fixes it.
Before:
bar
After:
screenshot-1
It would be better if the the icon size adjusts automatically like all the others icons do but I don't know how that is possible.
And, thank you all who made this applet.

**Comment by jaszhix** [comment]
@mswiszcz I forked this project as [Icing Task Manager](https://github.com/jaszhix/icingtaskmanager) and integrated your pull request as a part of the initial commit.

**Comment by mswiszcz** [comment]
@jaszhix Good job, there is also Russian translation pending as PR on my repo, you may want to add this also :wink:

**Comment by jaszhix** [comment]
@mswiszcz Thanks, I'll look into the other PRs later this week! One caveat with the icon resizing, I had to restart Cinnamon to see the change. So mileage may vary. I'll dig into the API docs some more and investigate.

**Comment by jaszhix** [comment]
@mswiszcz Russian translation was [added](https://github.com/jaszhix/icingtaskmanager/commit/46d9444cc4d6cd876b28631a7098fc9823d5e065).

**Pull request closed without merging**
