### PR TITLE
Added two features: move to monitor and open new app keybinding

### PR DESCRIPTION
**Pull request by Beanow**
## Move to monitor.
* `<Super><Shift>Left` and `<Super><Shift>Right` move the currently active window left or right from your current monitor.
* In the right click menu "Move to monitor X" is available for each monitor you have.

## Open new app window keybinding.
Using `<Super><Shift>Number` will open a new app instead of focus it.

These features are based off of the 2.7.5 release, rather than the current development version.

### CODE REVIEW

**Comment by jake-phy** [comment]
Yes those are both great developments.

**Comment by jake-phy** [comment]
I'm sorry it took so long to implement this.  I had to merge everything manually.  Are you able to test this and make sure it is still working?

**Comment by Beanow** [comment]
Couple of bugs I found:
* Left and Right should be swapped for window moving. (Tested on triple monitor setup)
* The monitor number is not displayed correctly, all of them are "Move to monitor {0}".

**Comment by jake-phy** [comment]
Ok thanks for testing.  I will make the changes.

-----Original Message-----

**Comment by jake-phy** [comment]
Ok this should be working now.

**Comment by Beanow** [comment]
The changes look good to me now. A new bug came up but I'll make a new issue for it.

**Pull request closed without merging**
